apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../upstream
- virtualservice.yaml
- networkpolicy_denyall.yaml
- networkpolicy_whereami.yaml
- sidecar.yaml
configMapGenerator:
- behavior: merge
  literals:
  - TRACE_SAMPLING_RATIO="0"
  name: whereami-configmap
patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/type
      value: ClusterIP
  target:
    kind: Service
    name: whereami
